# Generated by Django 6.0.6 on 2026-06-23 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'El número de teléfono debe ingresarse en el formato: "+999999999". Hasta 15 dígitos permitidos.')]),
        ),
    ]
