# Generated by Django 6.0.6 on 2026-06-23 04:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialproducto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s]+$', 'La categoría solo debe contener letras y números.')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe tener al menos 3 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'El precio debe ser mayor a 0.')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El stock no puede ser negativo.')]),
        ),
    ]
