# Generated by Django 6.0.6 on 2026-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_pedido_detallepedido_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
