@startuml arquitectura_mvt
!theme bluegray
title Arquitectura MVT + SPA — Treddy

skinparam componentStyle rectangle
skinparam ArrowFontSize 10

node "Cliente (Navegador Web)" as browser {
    [HTML5 / CSS Variables]
    [Fetch API (AJAX/SPA)]
    [SweetAlert2 (Alertas)]
    [NProgress (Barra progreso)]
    [Bootstrap 5]
}

cloud "Supabase Cloud" as cloud {
    database "PostgreSQL 17" as db {
        [usuarios_usuario]
        [productos_producto]
        [productos_historialproducto]
        [productos_favorito]
        [productos_pedido]
        [productos_detallepedido]
        [django_session]
    }
}

node "Servidor Django 6 (Backend)" as django {
    package "Capa de Lógica de Negocio (Service Layer)" as services {
        [procesar_checkout()]
    }

    package "Capa de Presentación (Template Layer)" as templates {
        [base.html (SPA Shell)]
        [dashboards/admin.html]
        [dashboards/cliente.html]
        [dashboards/vendedor.html]
        [productos/partials/*.html]
        [usuarios/partials/*.html]
        [factura_pedido.html (xhtml2pdf)]
    }

    package "Capa Lógica (View Layer)" as views {
        [CustomLoginView]
        [dashboard_view (Strategy Pattern)]
        [producto_list / create / update / delete]
        [toggle_favorito / favoritos_list]
        [add_to_cart / view_cart / checkout]
        [pedidos_list / historial_list]
        [download_pedido_pdf]
    }

    package "Capa de Datos (Model Layer)" as models {
        [Usuario (AbstractUser)]
        [Producto]
        [HistorialProducto (Observer)]
        [Favorito]
        [Pedido / DetallePedido]
    }

    package "URLs / Router" as urls {
        [treddy_project/urls.py]
        [usuarios/urls.py]
        [productos/urls.py]
    }

    package "Formularios (Forms)" as forms {
        [CustomLoginForm]
        [CustomRegistroForm]
        [AdminRegistroForm]
        [ProductoForm]
        [EditarPerfilForm]
    }
}

node "Configuraciones & Seguridad" as config {
    [.env (django-environ)]
    [django-axes (Fuerza Bruta)]
}

browser <--> views : "HTTP / AJAX (GET, POST)"
urls --> views : "dispatch()"
views --> services : "delega"
services <--> models : "Transacciones"
views <--> models : "ORM QuerySet"
views --> templates : "render(context)"
templates --> browser : "HTML Parcial / Completo"
forms --> views : "validate()"
models <--> db : "psycopg2 / dj-database-url"
config --> django : "aplica seguridad"

@enduml
